language: ruby
rvm:
  - 2.6.3

script: 
  - set -e
  - bundle install
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --disable-external

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - openssh-client

sudo: false

cache: bundler

before_deploy:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$kartolo_klim")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after _site/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master

notifications:
  email: false