version: '3'
services:
  site:
    command: jekyll serve --watch --force_polling --verbose --incremental
    image: jekyll/jekyll:latest
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
